model_list:
 - model_name: simple-xeon
   litellm_params:
     model: openai/microsoft/phi-2
     api_key: "fake-key"
     api_base: os.environ/XEON_API_BASE
     mode: completion
     temperature: 0.7
     stop: "<|end|>"
     bos_token: "<|endoftext|>"
     eos_token: "<|endoftext|>"
 - model_name: complex-gaudi
   litellm_params:
     model: openai/standard-granite-31-8b-instruct
     api_key: "fake-key" 
     api_base: os.environ/GAUDI_API_BASE
     mode: completion
     temperature: 0.1
     stop: "<|end|>"
     bos_token: "<|endoftext|>"
     eos_token: "<|endoftext|>"
general_settings: 
 master_key: sk-1234 
 custom_auth: custom_auth.user_api_key_auth
 log_raw_request_response: True
 set_verbose: false
cache: false
litellm_settings:
  drop_params: True
  log_raw_request_response: True
  return_response_headers: true
  verbose: false
  callbacks:
    - custom_router.proxy_handler_instance
#guardrails:
#  - guardrail_name: route-annotator
#    litellm_params:
#      guardrail: custom_callbacks.RouteGuardrail   # MODULE.Class (not an instance)
#      mode: post_call   
router_settings:
  num_retries: 2
  timeout: 30  