# Base image for the modelcar Granite image
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.4 as base

# Install necessary Python dependencies
RUN microdnf -y install git git-lfs python3-pip && \
    microdnf clean all

# Install Hugging Face libraries
RUN pip3 install torch transformers huggingface-hub

RUN python3 -c "\
from huggingface_hub import snapshot_download; \
snapshot_download(repo_id='microsoft/phi-2', local_dir='/models', allow_patterns=['*.safetensors', '*.json', '*.txt']); \
snapshot_download(repo_id='haritzpuerto/phi-2-dcot', local_dir='/models/lora/phi-2-dcot', allow_patterns=['*.safetensors', '*.json', '*.txt']); \
snapshot_download(repo_id='petualang/Phi2-Doctor28e', local_dir='/models/lora/phi2-doctor28e', allow_patterns=['*.safetensors', '*.json', '*.txt']) "

# Final image containing only the essential model files
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.4  

# Copy only the necessary model files from the base image
COPY --from=base /models /models

# Set the user to 1001
USER 1001
