---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: phi2-with-adapters
    serving.kserve.io/deploymentMode: RawDeployment
  name: vllm
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '1'
          memory: 4Gi
          nvidia.com/gpu: '1'
      runtime: vllm
      storageUri: oci://quay.io/ckavili/phi2-modelcar:0.0.5
    tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule